#pragma once

#define FEED_VERSION_MAJOR 1
#define FEED_VERSION_MINOR 16
#define FEED_VERSION_PATCH 0
#define FEED_VERSION_BUILD 4

#define FEED_VERSION "1.16.0-beta.4"
#define FEED_VERSION_NUM FEED_VERSION_MAJOR, FEED_VERSION_MINOR, FEED_VERSION_PATCH, FEED_VERSION_BUILD
